version: '3.7'
services:
  db:
    image: mysql:8
    container_name: mysql-wifiportal
    restart: always
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=navekwifi
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3309:3306'
      
# Or Execute in terminal
# docker run -p 3309:3306 --name mysql-wifiportal -e MYSQL_ROOT_PASSWORD=root -d mysql:8

# // And Login to MySQL from terminal
# mysql --host=127.0.0.1 --port=3309 -u root -p
